language: python

matrix:
   include:
      - os: linux
        python: 3.7
        env:
          - PYCONDA=3.7
          - PYDIST=37
#      - os: linux
#        python: 3.6
#        env:
#          - PYCONDA=3.6
#          - PYDIST=36

branches:
  only:
  - master
  - "/^release-.*$/"
  - "/^v[0-9.]+/"
before_install:
- "sudo apt-get install gfortran"
#- "sudo apt-get install libhdf5-serial-dev"
- "wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh"
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- export NPY_DISTUTILS_APPEND_FLAGS=1
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
# - conda create -q -n test-environment python=${PYCONDA} setuptools numpy=1.14 scipy pandas matplotlib h5py sphinx sphinx_rtd_theme numpydoc nose mkl theano vtk=8.2.0 pytables

install: 
   - "conda create -q -n test-environment python=${PYCONDA} python=3.7"
   - "source activate test-environment"
   - "python conda_setup.py"
   - "python setup_develop.py develop no_feti"

script:
   - "nosetests"
   - "cd docs"
   - "make html"
   - "cd .."
#   - "python setup.py sdist"
#   - "ls dist"
#   - "python setup.py bdist_wheel"
#   - "ls dist"

#deploy:
#  provider: releases
#  api_key:
#    secure: $GITHUB_TOKEN
#  file_glob: true
#  file: dist/*
#      - "dist/amfe-0.2.tar.gz"
#      - "dist/amfe-0.2-cp${PYDIST}-cp${PYDIST}m-linux_x86_64.whl"
#  on:
#    tags: true
#    repo: c-meyer/AMfe
    # branch condition cannot be done if tags: true
    #branch:
    #  - master
    #  - "/^release-.*$"
#  skip_cleanup: true
